name: ride_clone
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utility pacakges
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  lottie: ^3.3.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Local Assets
  assets: 
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env

  # Local Fonts
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 800

# fluttter launcher icon related
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon-512.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon-512.png"
  remove_alpha_ios: true
