// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBidSPjwj9Upmw-Zq8aWCy3hxG5RF_4DCs',
    appId: '1:918224786787:ios:7f118323b5382f3965ef56',
    messagingSenderId: '918224786787',
    projectId: 'flutter-ride-df197',
    storageBucket: 'flutter-ride-df197.firebasestorage.app',
    iosBundleId: 'com.example.rideClone',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3HYAvWcXD3_7WosPfu1wVD3vfWzgSH7A',
    appId: '1:918224786787:android:e2afc1e65da120e865ef56',
    messagingSenderId: '918224786787',
    projectId: 'flutter-ride-df197',
    storageBucket: 'flutter-ride-df197.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-1JPfZzEe7w6ovcP1IS5YJF92DelAnV8',
    appId: '1:918224786787:web:04479d58cef0751865ef56',
    messagingSenderId: '918224786787',
    projectId: 'flutter-ride-df197',
    authDomain: 'flutter-ride-df197.firebaseapp.com',
    storageBucket: 'flutter-ride-df197.firebasestorage.app',
  );
}
